#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: install_clean_laravel
## @Creation date file: 02.02.2020, 22:00:36

#
#   Декларируем имя файла
#

declare -rx install_clean_laravel_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
    declare -rx main_run_script_path="$(pwd)"
    echo "Script runs from ${main_run_script_path}"
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
    check=1
    while [[ "${check}" -eq 1 ]]; do
        if [[ ! -f 'main.cfg' ]]; then
            if [[ "$(pwd)" != "/" ]]; then
                cd ../
            else
                cd ${main_run_script_path}
                check=0
                echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m"
                tput sgr0
                exit 1
            fi
        else
            check=0
            declare -rx main_project_path="$(pwd)"
            . "${main_project_path}/main.cfg"
            cd "${main_run_script_path}"
        fi
    done
fi

echo "Connect $(readlink -m ${install_clean_laravel_script_source})"

flag_install=0
path_ilara='/laravel_ecosystem_clean'
name_env=''
function_command_pack_disable=0

function chk_args_for_install_clean_laravel_script_source() {

    OPTIND=1

    while getopts "icp:n:" OPT; do
        case $OPT in
        i) flag_install=1 ;;
        c) function_command_pack_disable=1 ;;
        p) path_ilara="$OPTARG" ;;
        n) name_env="$OPTARG" ;;
        *) ;;
        esac
    done

    shift $(($OPTIND - 1))
    [ "${1:-}" = "--" ] && shift

    [[ "${path_ilara}" == 'root_path' ]] && path_ilara=''
    if [[ "${name_env}" == '' ]]; then
        # ${parameter//pattern/string}
        name_env=${path_ilara////}
    fi

}

function install_install_clean_laravel() {

    # composer global require laravel/installer;
    # export PATH=$HOME/.config/composer/vendor/bin:$PATH;

    #
    # require laravel 7.x version
    #
    echo -n "Install clean Laravel platform ? y/n [n]"
    read key
    if [[ "${key}" == "y" ]]; then
        [[ -d "${main_project_path}${path_ilara}" ]] || composer create-project --prefer-dist laravel/laravel "${name_env}"

        cd "${main_project_path}${path_ilara}"

        . "${main_project_path}/install_shared_packages"

        # cp -f "${main_project_path}/shared/webpack.mix.js" "${main_project_path}${path_ilara}/webpack.mix.js"

        cd "${main_project_path}"

    fi

}

function main_install_clean_laravel_script_source() {

    echo "Initialise main function of install_clean_laravel script source"

    chk_args_for_install_clean_laravel_script_source $@

    . "${main_project_path}/shared_library"

    if [[ ${flag_install} -eq 1 ]]; then
        install_install_clean_laravel
    fi

    if [[ ! -d "${main_project_path}${path_ilara}" ]]; then
        echo "Not path ${main_project_path}${path_ilara}. Exit."
        exit 1
    fi

    function_command_pack

}

main_install_clean_laravel_script_source $@
