#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: install_laravel_backpack
## @Creation date file: 02.02.2020, 22:00:36

#
#   Декларируем имя файла
#

declare -rx install_laravel_backpack_script_source="$BASH_SOURCE"

if [[ -z "${main_run_script_path}" ]]; then
    declare -rx main_run_script_path="$(pwd)"
    echo "Script runs from ${main_run_script_path}"
fi

#
#   Подключаем общую библиотеку и общую конфигурацию
#

if [[ -z "${main_cfg_script_source}" ]]; then
    check=1
    while [[ "${check}" -eq 1 ]]; do
        if [[ ! -f 'main.cfg' ]]; then
            if [[ "$(pwd)" != "/" ]]; then
                cd ../
            else
                cd ${main_run_script_path}
                check=0
                echo '\e[47;31m'"!!! Not found configuration shared file !!!\033[0m"
                tput sgr0
                exit 1
            fi
        else
            check=0
            declare -rx main_project_path="$(pwd)"
            . "${main_project_path}/main.cfg"
            cd "${main_run_script_path}"
        fi
    done
fi

echo "Connect $(readlink -m ${install_laravel_backpack_script_source})"

function install_install_laravel_backpack() {

    if [[ ${flag_install} -eq 1 ]]; then
        echo -n "Install backpack ? y/n [n]"
        read key
        if [[ "${key}" == "y" ]]; then
            # install composer
            cd "${main_project_path}${path_ilara}"
            packages=(
                'backpack/crud'
                'backpack/generators --dev'
                'laracasts/generators --dev'
                'backpack/permissionmanager'
                'laracasts/flash'
            )

            for i in ${!packages[*]}; do
                composer require ${packages[$i]}
            done
            if [[ -d app/Http/Controllers/Auth ]]; then
                echo -n "Delete laravel demo auth controllers ? y/n [n]"
                read key
                if [[ "${key}" == "y" ]]; then
                    rm -rf app/Http/Controllers/Auth #deletes laravel's demo auth controllers
                fi
            fi

            ### yarn install && yarn run dev;
            npm install
            php artisan backpack:install --elfinder=no
            php artisan migrate
            php artisan backpack:user --name="${main_full_name}" --email="${main_email}" --password="${main_password}"
            php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"
            php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config" # then First, add the Spatie\Permission\Traits\HasRoles trait to your User model(s)
            php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"
            npm install && npm run dev

            cd "${main_project_path}"

            require_enviroment_file 1
            set_base_permission 1

        fi
    fi

}

function main_install_laravel_backpack_script_source() {

    echo "Initialise main function of install_laravel_backpack script source"

    . "${main_project_path}/install_laravel_ecosystem_clean" -c -p '/laravel_ecosystem_backpack_probe' $@

    install_install_laravel_backpack $@
    function_command_pack 1
    reload_systemctl_service

}

main_install_laravel_backpack_script_source $@
